vim.cmd("colorscheme rose-pine-moon")
vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
vim.api.nvim_set_hl(0, "FloatBorder", { bg = "none" })
vim.api.nvim_set_hl(0, "FloatTitle", { bg = "none" })
vim.api.nvim_set_hl(0, "FloatFooter", { bg = "none" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "none" })
